name: Build Windows/Linux/macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            generator: "Visual Studio 17 2022"
            arch: x64
          - os: ubuntu-latest
            generator: "Unix Makefiles"
          - os: macos-latest
            generator: "Unix Makefiles"

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Настройка MSVC для Windows
      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          toolset: latest
          vsversion: 2022  # Правильное имя параметра

      - name: Run tests (macOS)
        if: runner.os == 'macOS'
        run: |
          # Подготовка среды
          export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$(pwd)/build
          
          # Запуск тестов с подробным выводом
          cd build
          for test in $(ls test/lab*); do
            echo "Running $test..."
            ./$test || echo "Test $test failed"
          done
      # Установка зависимостей для Linux/macOS
      - name: Install dependencies
        if: matrix.os != 'windows-latest'
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Configure CMake
        run: cmake -B build -G "${{ matrix.generator }}"

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: cd build && ctest --output-on-failure

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build
          path: build/
